interfaces:
  eth1:
    description: 'To vpplab shared LAN'
    mtu: 1500
    lcp: eth1
    addresses: [ 192.0.2.254/24, 2001:db8:8298::fe/64 ]
  eth2:
    description: 'To vpp2'
    mtu: 1500
    lcp: eth2
    addresses: [ 10.0.0.16/31, 2001:db8:0:1::1/64 ]
loopbacks:
  loop0:
    description: 'vpp1'
    lcp: loop0
    addresses: [ 10.0.0.1/32, 2001:db8::1/128 ]
